name: Build and Deploy Godot Game

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Godot Export
        uses: firebelley/godot-export@v6.0.0
